default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= CREDENTIALS.dig(:database, :database) %>
  username: <%= CREDENTIALS.dig(:database, :username) %>
  password: <%= CREDENTIALS.dig(:database, :password) %>
  host: <%= CREDENTIALS.dig(:database, :host) %>

test:
  <<: *default
  database: <%= CREDENTIALS.dig(:database, :database) %>
  username: <%= CREDENTIALS.dig(:database, :username) %>
  password: <%= CREDENTIALS.dig(:database, :password) %>
  host: <%= CREDENTIALS.dig(:database, :host) %>

staging:
  <<: *default
  database: <%= CREDENTIALS.dig(:database, :database) %>
  username: <%= CREDENTIALS.dig(:database, :username) %>
  password: <%= CREDENTIALS.dig(:database, :password) %>
  url: <%= CREDENTIALS.dig(:database, :url) %>

production:
  <<: *default
  database: <%= CREDENTIALS.dig(:database, :database) %>
  username: <%= CREDENTIALS.dig(:database, :username) %>
  password: <%= CREDENTIALS.dig(:database, :password) %>
  url: <%= CREDENTIALS.dig(:database, :url) %>
